/*******************************************************************************
 This file is part of FeCl.
 
 Copyright (c) 2015, Etienne Pierre-Doray, INRS
 Copyright (c) 2015, Leszek Szczecinski, INRS
 All rights reserved.
 
 FeCl is free software: you can redistribute it and/or modify
 it under the terms of the Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 FeCl is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the Lesser General Public License
 along with FeCl.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

#ifndef FEC_PUNCTURED_TURBO_H
#define FEC_PUNCTURED_TURBO_H

#include <boost/serialization/export.hpp>

#include "Turbo.h"

namespace fec {
  
  /**
   *  This class represents a turbo encode / decoder.
   *  It offers methods encode and to decode data given a Turbo::Structure.
   *
   *  The structure of the parity bits generated by a Turbo object is as follow
   *
   *    | syst | systTail | convOutput1 | tailOutpu1 | convOutput2 | tailOutpu2 | ... |
   *
   *  where syst are the systematic bits, systTail are the tail bit
   *  added to the msg for termination of the constituents 1, 2, ..., respectively,
   *  convOutputX and tailOutputX are the output parity of the  msg and the tail
   *  generated by the constituent convolutional code X.
   *
   *  The structure of the extrinsic information is the case of serial decoding
   *
   *    | msg | systTail |
   *
   *  where msg are the extrinsic msg L-values generated by the last constituent
   *  code involved in each msg bit.
   *
   *  And in the case of parallel decoding
   *
   *    | msg1 | systTail1 | msg2 | systTail2 | ... |
   *
   *  where msgX are the extrinsic msg L-values generated by the constituent code X
   *  and systTailX are the tail bit added to the msg
   *  for termination of the constituent X.
   */
  class PuncturedTurbo : public Turbo
  {
    friend class boost::serialization::access;
  public:
    struct Lte3Gpp : public Turbo::Lte3Gpp {
    public:
      //static Structure structure();
      //static PuncturedTurbo codec();
    };
    
    /**
     *  This class represents a convolutional code structure.
     *  It provides a usefull interface to store and acces the structure information.
     */
    class Structure : public Turbo::Structure {
      friend class ::boost::serialization::access;
    public:
      Structure() = default;
      Structure(const EncoderOptions&, const PunctureOptions&, const DecoderOptions&);
      Structure(const EncoderOptions&, const PunctureOptions&);
      virtual ~Structure() = default;
      
      virtual const char * get_key() const;
      
      virtual void setEncoderOptions(const EncoderOptions& encoder);
      virtual void setPunctureOptions(const PunctureOptions& puncture);
      
      inline Permutation permutation() const {return permutation_;}
      
      virtual bool check(std::vector<BitField<size_t>>::const_iterator parity) const;
      virtual void encode(std::vector<BitField<size_t>>::const_iterator msg, std::vector<BitField<size_t>>::iterator parity) const;
      
    private:
      template <typename Archive>
      void serialize(Archive & ar, const unsigned int version) {
        using namespace boost::serialization;
        ar & ::BOOST_SERIALIZATION_BASE_OBJECT_NVP(Turbo::Structure);
        ar & ::BOOST_SERIALIZATION_NVP(permutation_);
      }
      
      Permutation permutation_;
    };
    
    PuncturedTurbo(const Structure& structure, int workGroupSize = 8);
    PuncturedTurbo(const EncoderOptions& encoder, const PunctureOptions& puncture, const DecoderOptions& decoder, int workGroupSize = 8);
    PuncturedTurbo(const EncoderOptions& encoder, const PunctureOptions& puncture, int workGroupSize = 8);
    PuncturedTurbo(const PuncturedTurbo& other) {*this = other;}
    virtual ~PuncturedTurbo() = default;
    PuncturedTurbo& operator=(const PuncturedTurbo& other) {Codec::operator=(other); structure_ = std::unique_ptr<Structure>(new Structure(other.structure())); return *this;}
    
    virtual const char * get_key() const;
    
    virtual size_t paritySize() const {return structure().permutation().outputSize();} /**< Access the size of the parity in each code bloc. */
    
    inline const Structure& structure() const {return dynamic_cast<const Structure&>(Codec::structure());}
    void setPunctureOptions(const PunctureOptions& puncture) {structure().setPunctureOptions(puncture);}
    
  protected:
    PuncturedTurbo() = default;
    
    inline Structure& structure() {return dynamic_cast<Structure&>(Codec::structure());}
    
    virtual void decodeBlocks(std::vector<LlrType>::const_iterator parity, std::vector<BitField<size_t>>::iterator msg, size_t n) const;
    virtual void soDecodeBlocks(InputIterator input, OutputIterator output, size_t n) const;
    
  private:
    template <typename Archive>
    void serialize(Archive & ar, const unsigned int version) {
      using namespace boost::serialization;
      ar.template register_type<Structure>();
      ar & ::BOOST_SERIALIZATION_BASE_OBJECT_NVP(Turbo);
    }
  };
  
}

BOOST_CLASS_EXPORT_KEY(fec::PuncturedTurbo);
BOOST_CLASS_TYPE_INFO(fec::PuncturedTurbo,extended_type_info_no_rtti<fec::PuncturedTurbo>);
BOOST_CLASS_EXPORT_KEY(fec::PuncturedTurbo::Structure);
BOOST_CLASS_TYPE_INFO(fec::PuncturedTurbo::Structure,extended_type_info_no_rtti<fec::PuncturedTurbo::Structure>);


#endif
