/*******************************************************************************
 Copyright (c) 2015, Etienne Pierre-Doray, INRS
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 * Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 
 * Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 Declaration of LdpcCode class
 ******************************************************************************/

#ifndef LDPC_CODE_H
#define LDPC_CODE_H

#include <thread>
#include <random>
#include <chrono>
#include <algorithm>

#include <boost/serialization/export.hpp>

#include "../Code.h"
#include "../Structure/BitMatrix.h"

namespace fec {

/**
 *  This class represents an ldpc encode / decoder.
 *  It offers methods encode and to decode data given an Structure.
 *
 *  The structure of the parity bits generated by an LdpcCode object is as follow.
 *
 *    | syst | parity |
 *
 *  where syst are the systematic msg bits and parity are the added parity required
 *  to create a consistent bloc.
 *
 *  The structure of the extrinsic information is the case
 *
 *    | check1 | check2 | ... |
 *
 *  where checkX are the messages at the last iteration from the check node X 
 *  that would be transmitted to the connected bit nodes at the next iteration.
 */
class LdpcCode : public Code
{
  friend class boost::serialization::access;
public:
  /**
   *  Decoder type
   *  This specifies the decode algorithm used in decoding.
   */
  enum DecoderType {
    TrueBp, /**< No approximation is used and the boxplus formula is computed using standard implementation */
    MinSumBp, /**< The minsum approximation is used instead of the boxplus formula */
  };
  
  /**
   *  This class represents a ldpc code structure.
   *  It provides a usefull interface to store and acces the structure information.
   */
  class Structure : public Code::Structure {
    friend class ::boost::serialization::access;
  public:
    
    static SparseBitMatrix gallagerConstruction(size_t n, size_t wc, size_t wr);
    
    Structure() = default;
    Structure(const SparseBitMatrix& H, size_t iterationCount = 50, DecoderType type = MinSumBp);
    Structure(SparseBitMatrix&& H, size_t iterationCount = 50, DecoderType type = MinSumBp);
    virtual ~Structure() = default;
    
    virtual const char * get_key() const;
    
    virtual Code::Structure::Type type() const {return Code::Structure::Ldpc;}
    
    inline const SparseBitMatrix& parityCheck() const {return H_;}
    
    inline DecoderType decoderType() const {return decoderType_;}
    inline size_t iterationCount() const {return iterationCount_;}
    
    inline void setIterationCount(size_t count) {iterationCount_ = count;}
    inline void setDecoderType(DecoderType type) {decoderType_ = type;}
    
    void syndrome(std::vector<uint8_t>::const_iterator parity, std::vector<uint8_t>::iterator syndrome) const;
    bool check(std::vector<uint8_t>::const_iterator parity) const;
    void encode(std::vector<uint8_t>::const_iterator msg, std::vector<uint8_t>::iterator parity) const;
    
  private:
    template <typename Archive>
    void serialize(Archive & ar, const unsigned int version) {
      using namespace boost::serialization;
      ar & ::BOOST_SERIALIZATION_BASE_OBJECT_NVP(Code::Structure);
      ar & ::BOOST_SERIALIZATION_NVP(H_);
      ar & ::BOOST_SERIALIZATION_NVP(DC_);
      ar & ::BOOST_SERIALIZATION_NVP(T_);
      ar & ::BOOST_SERIALIZATION_NVP(A_);
      ar & ::BOOST_SERIALIZATION_NVP(B_);
      ar & ::BOOST_SERIALIZATION_NVP(decoderType_);
      ar & ::BOOST_SERIALIZATION_NVP(iterationCount_);
    }
    
    void computeGeneratorMatrix(SparseBitMatrix&& H);
    
    SparseBitMatrix H_;
    SparseBitMatrix DC_;
    SparseBitMatrix T_;
    SparseBitMatrix A_;
    SparseBitMatrix B_;
    
    DecoderType decoderType_;
    size_t iterationCount_;
  };
  
  
  LdpcCode(const Structure& structure, int workGroupdSize = 4);
  virtual ~LdpcCode() = default;
  
  virtual const char * get_key() const;
  
  //virtual void syndrome(const std::vector<uint8_t>& parity, std::vector<uint8_t>& syndrome) const;
  
  inline size_t getIterationCount() const {return structure_.iterationCount();}
  inline void setIterationCount(size_t count) {structure_.setIterationCount(count);}
  
protected:
  LdpcCode() = default;
  
  virtual void encodeBloc(std::vector<uint8_t>::const_iterator messageIt, std::vector<uint8_t>::iterator parityIt) const;
  virtual void appDecodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<LlrType>::const_iterator extrinsicIn, std::vector<LlrType>::iterator messageOut, std::vector<LlrType>::iterator extrinsicOut, size_t n) const;
  virtual void softOutDecodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<LlrType>::iterator messageOut, size_t n) const;
  virtual void decodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<uint8_t>::iterator messageOut, size_t n) const;
  
private:
  template <typename Archive>
  void serialize(Archive & ar, const unsigned int version) {
    using namespace boost::serialization;
    ar & ::BOOST_SERIALIZATION_NVP(structure_);
    ar.template register_type<Structure>();
    ar & ::BOOST_SERIALIZATION_BASE_OBJECT_NVP(Code);
  }
  
  Structure structure_;
};
  
}

BOOST_CLASS_EXPORT_KEY(fec::LdpcCode);
BOOST_CLASS_TYPE_INFO(fec::LdpcCode,extended_type_info_no_rtti<fec::LdpcCode>);
BOOST_CLASS_EXPORT_KEY(fec::LdpcCode::Structure);
BOOST_CLASS_TYPE_INFO(fec::LdpcCode::Structure,extended_type_info_no_rtti<fec::LdpcCode::Structure>);

#endif
