/*******************************************************************************
 Copyright (c) 2015, Etienne Pierre-Doray, INRS
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 * Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 
 * Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 Declaration of LdpcCode class
 ******************************************************************************/

#ifndef LDPC_CODE_H
#define LDPC_CODE_H

#include <thread>

#include <boost/serialization/export.hpp>

#include "../Code.h"
#include "../CodeStructure/LdpcCodeStructure.h"
#include "BpDecoder/BpDecoder.h"

namespace fec {

/**
 *  This class represents an ldpc encode / decoder.
 *  It offers methods encode and to decode data given an LdpcCodeStructure.
 *  The structure of the parity bits generated by an LdpcCode object is as follow.
 *
 *    | syst | parity |
 *
 *  where syst are the systematic msg bits and parity are the added parity required
 *  to create a consistent bloc.
 *  The structure of the extrinsic information is the case
 *
 *    | check1 | check2 | ... |
 *
 *  where checkX are the messages at the last iteration from the check node X 
 *  that would be transmitted to the connected bit nodes at the next iteration.
 */
class LdpcCode : public Code
{
  friend class boost::serialization::access;
public:
  LdpcCode(const LdpcCodeStructure& codeStructure, int workGroupdSize = 4);
  virtual ~LdpcCode() = default;
  
  virtual const char * get_key() const;
  
  virtual size_t msgSize() const {return codeStructure_.msgSize();}
  virtual size_t paritySize() const {return codeStructure_.paritySize();}
  virtual size_t extrinsicSize() const {return codeStructure_.parityCheck().size();}
  virtual const CodeStructure& structure() const {return codeStructure_;}
  
  //virtual void syndrome(const std::vector<uint8_t>& parity, std::vector<uint8_t>& syndrome) const;
  
  inline size_t getIterationCount() const {return codeStructure_.iterationCount();}
  inline void setIterationCount(size_t count) {codeStructure_.setIterationCount(count);}
  
protected:
  LdpcCode() = default;
  
  virtual void encodeBloc(std::vector<uint8_t>::const_iterator messageIt, std::vector<uint8_t>::iterator parityIt) const;
  virtual void appDecodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<LlrType>::const_iterator extrinsicIn, std::vector<LlrType>::iterator messageOut, std::vector<LlrType>::iterator extrinsicOut, size_t n) const;
  virtual void softOutDecodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<LlrType>::iterator messageOut, size_t n) const;
  virtual void decodeNBloc(std::vector<LlrType>::const_iterator parityIn, std::vector<uint8_t>::iterator messageOut, size_t n) const;
  
private:
  template <typename Archive>
  void serialize(Archive & ar, const unsigned int version) {
    using namespace boost::serialization;
    ar & ::BOOST_SERIALIZATION_BASE_OBJECT_NVP(Code);
    ar & ::BOOST_SERIALIZATION_NVP(codeStructure_);
  }
  
  LdpcCodeStructure codeStructure_;
};
  
}

BOOST_CLASS_EXPORT_KEY(fec::LdpcCode);
BOOST_CLASS_TYPE_INFO(fec::LdpcCode,extended_type_info_no_rtti<fec::LdpcCode>);

#endif
